### ISSUE TITLE
Broken link on README

### ISSUE THREAD

**Issue by sfikas** [Transkribus/TranskribusBaseLineEvaluationScheme#1]
Link doesn't work:
    https://transkribus.eu/TranskribusBaseLineMetricTool/apidocs/index.html

**Comment by gundramleifert** [comment]
It will be fixed in the next minutes. Take a look at https://github.com/Transkribus/TranskribusBaseLineMetricTool/blob/master/line_metric_draft.pdf for the formulars and https://github.com/Transkribus/TranskribusBaseLineMetricTool/blob/master/src/main/java/eu/transkribus/baselinemetrictool/Metric_BL_eval.java to see, how it can be used.
