### ISSUE TITLE
CMD output

### ISSUE THREAD

**Issue by diemmarkus** [Transkribus/TranskribusBaseLineEvaluationScheme#2]
currently we get this cmd output:

```
#######Final Evaluation#######
Avg (over Pages) Avg Precision: 0,9333
Avg (over Pages) Avg Recall: 0,9461
Avg (over Pages) Avg F-Measure: 0,9397
```

It would be nice to additionally get the numbers (`# tp, # fp, # fn`)

**Comment by TobiasGruening** [comment]
Since, the classical precision/recall measure is adapted, you will not get #tp, ... 
But you can calculate something very similar (hopefully expressing, what you want). You can calculate #trueHypothesis (#tH); #falseHypothesis (#fH); #trueGroundtruth (#tG); #falseGroundtruth (#fG)

An addtitional parameter "tTV" which is per default set to -1.0 is integrated.
If you set this parameter to a value between 0 and 1, you get #tH #fH #tG #fG in the following manner:
a HYPOTHESIS line counts as tH if its presision is greater tTV (fH if it is smaller)
a GROUNDTRUTH line counts as tG if its recall is greater tTV (fG if it is smaller)

This leads to #hypo = #tH + #fH and #groundtruth = #tG + #fG.
This is already implemented and I will commit it, if it is ok for?!
